version: '3'

networks:
  apps-network:
    driver: bridge

services:
  reverse_proxy:
    image: nginx:1.23.3
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./nginx/env/dev.env
    volumes:
      #--- nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates/:/etc/nginx/templates/
      - ./www/:/var/www/html/
      - ./logs/:/var/log/nginx/
    networks:
      - apps-network